### PR TITLE
Adds usage instructions

### PR DESCRIPTION
**Pull request by sagech**
Adds a call-to-action to the "New" page on the "Getting Started" page. Also includes a code snippet to import BITBOX if users do not want to use the scaffolding tool.

### CODE REVIEW

**Comment by cgcardona** [comment]
@gitcash tip $1 to @sagech

**Comment by cgcardona** [comment]
Thank you!

**Comment by alwaysAn0n** [comment]
@cgcardona , no dollar signs. Try it like this!

@GitCash tip 1 usd to @sagech

**Comment by GitCash** [comment]
Hey **sagech**, user **alwaysAn0n** tipped you **1901 bits** in Bitcoin Cash ( ~ **$1** ).

*[Click here to claim it!](https://gitcash.io/claim/sagech)*

You can also add the "thumbs down" reaction to **alwaysAn0n**'s comment above to prevent future tips.

**Pull request merged**
