### PR TITLE
Wallets Chapter

### PR DESCRIPTION
**Pull request by davidshares**
Adding Chapter 5 section for wallets

### CODE REVIEW

**Comment by cgcardona** [comment]
Thank you! I just want to confirm this is from the First Edition of Mastering Bitcoin. The [second edition](https://github.com/bitcoinbook/bitcoinbook#mastering-bitcoin---second-edition) is [Creative-Commons-NoDerivatives](https://creativecommons.org/licenses/by-nc-nd/4.0/)

**Comment by pzenger** [comment]
Site has been re-built using gatsby and markdown files since this was open.  
I will look into migrating this chapter over to the new format.

**Comment by davidshares** [comment]
> Thank you! I just want to confirm this is from the First Edition of Mastering Bitcoin. The [second edition](https://github.com/bitcoinbook/bitcoinbook#mastering-bitcoin---second-edition) is [Creative-Commons-NoDerivatives](https://creativecommons.org/licenses/by-nc-nd/4.0/)

To confirm, https://github.com/bitcoinbook/bitcoinbook#mastering-bitcoin---second-edition under "Mastering Bitcoin - Second Edition" it is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.

**Comment by pzenger** [comment]
Closing this PR for now as it is currently inactive and the project structure has since changed.  
If we want to capture this work, please create an issue.

**Pull request closed without merging**
