### PR TITLE
Correct address.md example and add a link to locktime in transactionBuilder.md

### PR DESCRIPTION
**Pull request by kralux**
Changed the query address to match the returned content (see legacyAddress and the rest). The address in the query had nothing to do with the returned data.

### CODE REVIEW

**Comment by kralux** [comment]
Also added a link for the locktime to give a description of how to use it since some people may not be familiar with what the actual number represents (even though they may already know the general concept of locktime)

**Comment by kralux** [comment]
Added a small paragraph at the top of the TransactionBuilder to explain what it is and how to use it. I felt like a bit of information is needed in the doc else it is mandatory to go over all the examples below to start to understand what needs to be done to create a transaction. It is nice to give a head's up up front.

**Comment by SpendBCH** [comment]
Much more informative

Thank you! @GitCash 512 bits for @kralux

**Comment by GitCash** [comment]
Hey **kralux**, user **SpendBCH** tipped you **512 bits** in Bitcoin Cash ( ~ **$0.065** ).

*[Click here to claim it!](https://gitcash.io/claim/kralux)*

You can also add the "thumbs down" reaction to **SpendBCH**'s comment above to prevent future tips.

**Pull request merged**
